### ISSUE TITLE
Consider adding fantasy-land and static-land compatibility objects

### ISSUE THREAD

**Issue by iwburns** [iwburns/tupperware#42]
Might be useful for nullshield to be compatible with other libraries that follow the fantasy-land / static-land specifications.

More info on each can be found at [fantasy-land](https://github.com/fantasyland/fantasy-land) and [static-land](https://github.com/rpominov/static-land).

My initial thoughts would be to provide new types like `nullshield/fantasy-land/Option` and `nullsheild/static-land/Option` that adhere to the given specifications and then provide `to` / `from` conversions where necessary.

**Comment by ryanguill** [comment]
Currently im not all that interested in fantasy-land or static-land compliant implementations.  I _think_ anyone who is will probably be more interested in a broader, already existing library.  Just my 2 cents though.

**Comment by iwburns** [comment]
That's probably fair.  And I think if we wanted to do this in the future by having the to/from conversions as I said above, it could be done fairly easily without breaking changes (_I think_).

Marking this as deferred for now.  We can come back to it later or cancel it as we see fit.

**Comment by iwburns** [comment]
closing this for now.
