### ISSUE TITLE
Name change for library

### ISSUE THREAD

**Issue by iwburns** [iwburns/tupperware#53]
I wanted to pull this into a different issue so that we're not preventing progress in #50 by also having to choose a name in that issue.

Names that were suggested in #50 :
* `joinery` because `join` has a meaning in "monad-land" and because joinery in carpentry is kindof like "composition"
* `phial`  because it's a container
* `gershwin` because he is a _compose_ -r

New names since then:
* `edgecase` (or `edge-case`) because this lib should help you avoid them

Naming inspirations:
* anything related to containers
* anything related to composition
* or just a random word that sounds cool and isn't offensive

cc: @brycehipp @ryanguill

**Comment by iwburns** [comment]
Hey guys, I've been able to come up with a few others:

* `tupperware` - already on npm
* `fairing`
* `canteen` - already on npm
* `wrad` for WRAp Data (pronounced "rad")
* `may-be`
* `perhaps` - already on npm
* `perchance` - already on npm
* `mightbe`

I'm not _loving_ any of them, but of course some are better than others.  Also, I don't want this project to stall over picking a name.  At this point I'm not against going with something namespaced if we have to (which is why I listed the ones already on npm).

You guys have any thoughts on this?

Also, if (either or both of) you guys would rather not be a part of the naming process, that's totally fine with me, just say so.

cc: @ryanguill @brycehipp

**Comment by brycehipp** [comment]
Reminds me of this quote.

> There are only two hard things in Computer Science: cache invalidation and naming things.
> 
> -- Phil Karlton

Jokes aside, `wrad` seems to stick with me and I can't quite put my finger on it why. I don't think it flows too well with the intent of this package though, but maybe thats not terrible?

If I were to pick one that goes the best with the package's intent then I would say `tupperware` or `perhaps`. I lean toward `tupperware` since its more memorable.

**Comment by iwburns** [comment]
>Reminds me of this quote.[...]

Ha! Totally.

>Jokes aside,[...]

I agree, `wrad` seems good for no reason at all, and maybe that's a good thing.

>If I were to[...]

I really like `tupperware` as well tbh, but it annoys me that it would have to be namespaced.  I guess it's not the end of the world and I should just get over it, but it just irks me that I can't think of a good name that's available globally.

**Comment by iwburns** [comment]
Alright, after giving this some time, I think `tupperware` is the one to go with.  I'll just have to scope it and deal with that being slightly annoying.

I'll open it up here for final concerns/objections but I'd like to move this forward soon because I'm very tired of thinking about names.

**Comment by iwburns** [comment]
Oops, forgot to cc @brycehipp @ryanguill

**Comment by iwburns** [comment]
@brycehipp @ryanguill 

Alright guys, it has been two weeks and no concerns have been raised on this.

I'll go through the process in the next few days of re-naming and then re-publishing the current version up to npm under `iwburns/tupperware`.  I'll also need to do something to the `nullshield` package to signify that it is has moved and is no longer being maintained.

**Comment by ryanguill** [comment]
I'm sorry, I got busy in the middle of this conversation and wasn't able to see it through.  Personally I don't mind that it is namespaced - lots of projects are moving to namespaces anyway.

**Comment by iwburns** [comment]
no worries man, I know we're all busy.  Just trying to keep this from stalling too bad.

**Comment by iwburns** [comment]
alright, this is now published as `@iwburns/tupperware` [here](https://www.npmjs.com/package/@iwburns/tupperware)!
